puts "The students of my cohort at the Makers Academy Feb 2015"
puts "---------------------"
puts "Sam Joseph"
puts "Kieran Goodacre"
puts "Christopher Ward"
puts "Rizwan Ali"
puts "The Joker"
puts "Freddy Kruger"
puts "The Alien"
puts "Michael Corleone"
puts "Nurse Ratched"
